#server
server:
  port: 80 
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /   

#spring
spring:
  datasource:
    url: jdbc:mysql:///acdb?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#mybatis    
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*.xml
   
#logging
logging:
  level:
   com.ac: debug 
   
   
   
   
   
   
   
   
   
   
   
   
   
    
    
    
  
    
    
